[versions]
androidGradlePlugin = "8.1.0"
kotlin = "1.9.0"
androidxCore = "1.10.1"
androidxConcurrentFutures = "1.1.0"
androidxLifecycle = "2.6.1"
androidxAppCompat = "1.6.1"
androidxNavigation = "2.6.0"
androidxCameraX = "1.3.0-beta01"
material = "1.9.0"
junit4 = "4.13.2"
androidxTestExt = "1.1.5"
androidxEspresso = "3.5.1"
mediapipeTasks = "0.10.2"
kotlinxCoroutines = "1.7.3"
androidxComposeCompiler = "1.5.1"
androidxComposeBom = "2023.06.01"
googleAccompanist = "0.30.1"
androidxConstraintLayout = "1.0.1"
androidxActivity = "1.7.2"
koin = "3.4.2"
koinCompose = "3.4.5"
koinTest = "3.4.1"
androidxTestRunner = "1.5.2"
androidxTestCore = "1.5.0"
androidxFragment = "1.6.0"
androidxBenchmark = "1.1.1"
robolectric = "4.10.3"
androidxTestRules = "1.5.0"
androidxUiAutomator = "2.2.0"
androidxTestOrchestrator = "1.4.2"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "androidxConcurrentFutures" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidxCameraX" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCameraX" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCameraX" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCameraX" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
google-mediapipe-tasks-vision = { group = "com.google.mediapipe", name = "tasks-vision", version.ref = "mediapipeTasks" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
google-accompanist-themeadapter-m3 = { group = "com.google.accompanist", name = "accompanist-themeadapter-material3", version.ref = "googleAccompanist" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidxConstraintLayout" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidxComposeCompiler" }
io-insert-koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
io-insert-koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
io-insert-koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
io-insert-koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koinTest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-benchmark = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidxBenchmark" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidxFragment" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxUiAutomator" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTestOrchestrator" }

[bundles]
camerax = ["androidx-camera-core", "androidx-camera-camera2", "androidx-camera-view", "androidx-camera-lifecycle"]
navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
benchmark = { id = "androidx.benchmark", version.ref = "androidxBenchmark" }
